# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Mike Ortiz
description:      'Security Engineer, DFIR'
url:              https://ortizmj12.github.io
baseurl:          /

author:
  name:           'Mike Ortiz'
  url:            https://twitter.com/lorddicranius

paginate:         5

# Custom vars
version:          2.1.0

twitter:
  url:            https://www.twitter.com/lorddicranius
github:
  repo:           https://github.com/ortizmj12
