# Dependencies
markdown:         kramdown
gems:
- jekyll-paginate

# Permalinks
permalink:        pretty

# Setup
title:            Michael Ortiz
description:      'Security Engineer'
url:              https://ortizmj12.github.io
baseurl:          /

author:
  name:           'Michael Ortiz'
  url:            https://twitter.com/ortizmj12

paginate:         5

# Custom vars
#version:          2.1.0

twitter:
  url:            https://www.twitter.com/ortizmj12
github:
  repo:           https://github.com/ortizmj12
